# This is a basic workflow to help you get started with Actions

name: CI-CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Autenticando o usuário no Docker
        uses: docker/login-action@v2.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
          
      - name: Construindo a imagem e enviando para o DockerHub
        uses: docker/build-push-action@v3.0.0
        with:
          file: ./src/Dockerfile
          context: ./src
          push: true
          tags: |
            brunobrazil/kube-news:v2
            brunobrazil/kube-news:${{github.run_number}}
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps: 
      - uses: actions/checkout@v3
      
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Definindo o kube_config
        uses: Azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.k8s_CONFIG}}
          
      - name: Criando o deploy no kubernet
        uses: Azure/k8s-deploy@v3.1
        with:
          images: brunobrazil-kube-news:${{github.run_number}}
          manifests: |
            images: k8s/deployment.yaml
